### ISSUE TITLE
Environments

### ISSUE THREAD

**Issue by cfey** [leoschweizer/contentful-redux#12]
Hi,
it would be awesome if this library would support "Environments".
In my specific case, we got a staging build which should be connected to the staging environment from contentful

I can create PR but I couldn't figure out where to add the staging key information

**Comment by leoschweizer** [comment]
@cfey I didn't have the opportunity to look into contentful environments but this library _might_ work with environments as is. You can try to instantiate it like this:
```
export const { actions, reducer, middleware, selectors } = contentfulRedux({
    createClient,
    space: 'YOUR_SPACE_ID',
    accessToken: 'YOUR_ACCESS_TOKEN',
    stateSelector: state => state.contentful,
    clientParams: {
        environment: 'master'
    }
});
```

You might need to use a more recent version of the Contentful SDK (6+). This library has only been tested with version 5, but I don't see any changes that would break it.

**Comment by cfey** [comment]
You are right, works like charm!
Thanks for the fast response
